### ISSUE TITLE
Стикеры из Telegram

### ISSUE THREAD

**Issue by albertos1607** [umerov1999/Fenrir-for-VK#11]
Реализовать возможность импорта стикеров из Telegram (например, через создаваемого пользователем бота или сервер Utkacraft)

**Comment by albertos1607** [comment]
*поднять аналог Utkacraft

**Comment by albertos1607** [comment]
Думал что Utkacraft независимый от Sova V сервер, а нет

**Comment by umerov1999** [comment]
> Реализовать возможность импорта стикеров из Telegram (например, через создаваемого пользователем бота или сервер Utkacraft)

Ну ты можешь получить zip через бота и распаковать в папку /Downloads/Fenrir_Stikers

**Comment by albertos1607** [comment]
Ок, огромное спасибо за информацию.
