### ISSUE TITLE
Не меняют цвет при смене темы тематические иконки на Android 12

### ISSUE THREAD

**Issue by albertos1607** [umerov1999/Fenrir-for-VK#12]
При выборе тематической иконки в настройках приложения, она не меняет цвет при смене тем на устройстве и в самом приложении.

**Comment by contonice** [comment]
Pixel 4, android 13 полёт нормальный. Адаптивные цвета работают и меняются

**Comment by albertos1607** [comment]
> Pixel 4, android 13 полёт нормальный. Адаптивные цвета работают и иконки меняются

Да, я проверил, и правда все работает. Наверное проблема прошлого лаунчера (был Lawnchair 12)
