### ISSUE TITLE
Соответствие цвета иконки приложения таковой на splash-screen

### ISSUE THREAD

**Issue by GravaTharg** [umerov1999/Fenrir-for-VK#14]
У меня появилась идея: а что, если в случае изменения иконки приложения загрузочный экран сделать соответствующего цвета?
![Screenshot_20220524-231831_One UI Home](https://user-images.githubusercontent.com/71602682/170104916-fa70c276-afd6-4672-8b42-9ca299457fa2.png)
![Screenshot_20220524-231841_Fenrir VK](https://user-images.githubusercontent.com/71602682/170104926-0a56c2be-245d-4737-a8ea-d119344689be.png)

**Comment by umerov1999** [comment]
А то бы я не додумался так сделать) На андроиде ниже 12 это нельзя просто так сделать

**Comment by GravaTharg** [comment]
Понял) окей тогда
