### ISSUE TITLE
Как это понимать? Версия 2.94

### ISSUE THREAD

**Issue by VladislavR34** [umerov1999/Fenrir-for-VK#23]
![Screenshot_2022-07-28-20-09-55-701_dev ragnarok fenrir](https://user-images.githubusercontent.com/107295599/181513414-68078b6e-be8d-4bb1-86e1-a8e88dcf376a.jpg)
Просто без причины перестал пускать в сообщения!

**Comment by KovvalskiX** [comment]
попробуйте перелогиниться
