### ISSUE TITLE
Добавить возможность загрузки mp3 в музыку

### ISSUE THREAD

**Issue by contonice** [umerov1999/Fenrir-for-VK#25]
В ПК версии сайта ВКонтакте есть кнопка для загрузки своих mp3, а так же кнопка редактирования для изменения названия уже загруженных треков

**Comment by umerov1999** [comment]
Она есть, ищи

**Comment by contonice** [comment]
Либо я чего-то не понимаю, либо эта кнопка и есть то что я ищу, просто она не работает. Что должно происходить при её нажатии?
![Screenshot_20220831-212432~2](https://user-images.githubusercontent.com/80057672/187730289-26a9515a-06a1-47d1-8dd6-1a0f7ff3753d.png)

**Comment by contonice** [comment]
Ясно. Для таких же непонятливых как я напишу:
Для загрузки своих треков надо зайти во вкладку "На устройстве", найти нужный файл, открыть свойства и там будет заветная кнопка.
