### ISSUE TITLE
Удаление уведомлений после прочтения

### ISSUE THREAD

**Issue by contonice** [umerov1999/Fenrir-for-VK#29]
Было бы неплохо автоматически удалять уведомления о новых сообщениях после их прочтения.
Не знаю, есть ли с текущим кодом возможность это дописать...

**Comment by sabl1m** [comment]
Здравствуйте! Как с вами связаться? По поводу написать приложение.

**Comment by contonice** [comment]
В версии 2.105 уведомления при прочтении удаляются
