### ISSUE TITLE
Раздел "Музыка"

### ISSUE THREAD

**Issue by VladislavR34** [umerov1999/Fenrir-for-VK#32]
Мне Фенрир нравился тем, что в нем практически ничего лишнего. Да, есть баги, недоработки, но это терпимо. С последним обновлением 2.104 раздел "Музыка" стал почти как на оригинальном ВК. Столько лишнего появилось, сразу так непривычно и неудобно. Было лучше, когда в музыке только музыка. Не рекомендации, не устройства и прочая муйня. Скорее всего откачусь обратно до версии 2.102. 
P.s. Обновляюсь я исключительно ради исправлений и ради изменения приложения в лучшую сторону. Но здесь, как и в любом другом приложении (как сейчас модно), обновления только ухудшают приложение. Я не отрицаю, рекомендации музыки - это полезно. Но далеко не всем. Потому что те, кто пользуется Фенриром, они поэтому и пользуются, чтобы не видеть все лишнее, что есть в официальном ВК.

**Comment by umerov1999** [comment]
Можно выключить в настройках. Общие - каталог v2

**Comment by VladislavR34** [comment]
А, все, понял. Вопрос закрыт. 
Кстати, хорошая идея - предоставить выбор отображения музыки. Каждый выбирает, как ему нравится. Удобно.
